// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcF-vsmEmf7B73YHSRD7zd51xtgPXn3hw',
    appId: '1:475259128249:web:3a3979556bbb4953ce4e68',
    messagingSenderId: '475259128249',
    projectId: 'my-app-with-firebase-68d65',
    authDomain: 'my-app-with-firebase-68d65.firebaseapp.com',
    storageBucket: 'my-app-with-firebase-68d65.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHWJfFlzRbVDqKrKZi81jxAGYVK6Hxv5o',
    appId: '1:475259128249:android:871066dd8c274fbbce4e68',
    messagingSenderId: '475259128249',
    projectId: 'my-app-with-firebase-68d65',
    storageBucket: 'my-app-with-firebase-68d65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwBJFafh2gjXWTADODOmYc-MSLL1mBaLk',
    appId: '1:475259128249:ios:33116ccf93e05631ce4e68',
    messagingSenderId: '475259128249',
    projectId: 'my-app-with-firebase-68d65',
    storageBucket: 'my-app-with-firebase-68d65.appspot.com',
    iosBundleId: 'com.example.myAppWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwBJFafh2gjXWTADODOmYc-MSLL1mBaLk',
    appId: '1:475259128249:ios:33116ccf93e05631ce4e68',
    messagingSenderId: '475259128249',
    projectId: 'my-app-with-firebase-68d65',
    storageBucket: 'my-app-with-firebase-68d65.appspot.com',
    iosBundleId: 'com.example.myAppWithFirebase',
  );
}
